import type { Metadata } from 'next';
import { Fira_Mono } from 'next/font/google';
import './globals.scss';

const font = Fira_Mono({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	display: 'swap'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru' className={font.className}>
			<body>{children}</body>
		</html>
	);
}
